### ISSUE TITLE
typos in main.py

### ISSUE THREAD

**Issue by ronkinoz** [fauresystems/mqtt-observer#1]
Nice project! I'll be using this to monitor the status of a bunch of Pi's as they boot up and start running.

Anyway, a typo in main.py stopped this running under Ubuntu.
Two uses of QStyleFactoryscreate should be QStyleFactory.create.

    if platform.system() == 'Windows':
        if QSysInfo.windowsVersion() > QSysInfo.WV_WINDOWS7:
        QApplication.setStyle(QStyleFactory.create("Fusion"))
    else:
        QApplication.setStyle(QStyleFactoryscreate("Windows"))
    else:
        QApplication.setStyle(QStyleFactoryscreate("Windows"))

**Comment by fauresystems** [comment]
Thanks for reporting! Fixed and commited!
